config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  get 'static_pages/secret'
  devise_for :users
  resources :users
  resources :items
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_one :user
  has_many :join_table_cart_items
  has_many :items, through: :join_table_cart_items

  def total
    total = 0
    self.items.each do |item|
      total += item.price
    end
    return total
  end

end

app/models/create_join_order_item.rb
class CreateJoinOrderItem < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :picture
  validates :picture,
            presence: true

end

app/models/join_cart_item.rb
class JoinCartItem < ApplicationRecord

  before_create :already_exist?
  after_create :null

  belongs_to :cart
  belongs_to :item
end

app/models/join_order_item.rb
class JoinOrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item



end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord

  belongs_to :cart
  belongs_to :item

end

app/models/order.rb
class Order < ApplicationRecord

  after_create :order_mail
  after_create :order_cart

  belongs_to :user

  has_many :join_order_items
  has_many :items, through: :join_order_items

 
  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  after_create :welcome_send
    
   after_create :user_cart
  has_one :cart, dependent: :destroy
  has_many :items, through: :carts
  has_many :orders


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


   

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end

    def user_cart
      Cart.create(user_id: self.id)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user, only: [:show]

  def index
    @carts = Cart.all
    @carts_length = (Cart.find_by(user_id: current_user.id)).items.length
  end  

  def show
    @cart = Cart.find_by(user_id: params[:id])
  end
  
  def update
    @cart = Cart.find_by(user_id: current_user.id)
    new_item = JoinTableCartItem.create(cart_id: @cart.id, item_id: params[:id])

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end

  def destroy
    @user = current_user
    @item = Item.find_by(id: params[:id])
    @cart = Cart.find_by(user_id: current_user.id)
    @cart_item = JoinTableCartItem.find_by(cart_id: @cart.id, item_id: @item.id).destroy

    respond_to do |format|
      format.html { redirect_to cart_path(@user.id) }
    end
  end

  private

  def set_current_user
    @cart = Cart.find_by(user_id: params[:id])
    if current_user.id != @cart.user_id
      redirect_to root_path
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 before_action :authenticate_user!, except: [:index, :show]
  # before_action :authenticate_user!

  def index
  	@items = Item.all
  end

  def show
  	@item = Item.find(params[:id])
  end

   def update
   
    @cart = Cart.find_by(user_id: current_user.id)
    new_item = JoinTableCartItem.create(cart_id: @cart.id, item_id: params[:id])

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @item_price = params[:item_price]
  end

  def create
    # Before the rescue, at the beginning of the method
    @stripe_amount = 500
    begin
      customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
      })
      charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @stripe_amount,
      description: "Achat d'un produit",
      currency: 'eur',
      })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_order_path
    end
# After the rescue, if the payment succeeded
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_exists?, :check_user, only: [:show]
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_test_helper.rb
module BootstrapTestHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>


        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Samouraï Photo Cats !</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Achète la photo qui te plait</p>
                </div>
            </div>
        </header>
        <!-- Section-->
       <body>
  <div class="container">
    <h2 class="mb-4">Tous les chats</h2>
    <div class="row gx-4 gy-4 mb-3">

      <div class="col-sm-3">
        <img src="https://loremflickr.com/320/240?random=52"  class="card-img-top" alt="...">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Acheter cette photo</a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <img src="https://loremflickr.com/320/240?random=190"  class="card-img-top" alt="...">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Acheter cette photo</a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <img src="https://loremflickr.com/320/240?random=3"  class="card-img-top" alt="...">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Acheter cette photo</a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <img src="https://loremflickr.com/320/240?random=5"  class="card-img-top" alt="...">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Acheter cette photo</a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <img src="https://loremflickr.com/320/240?random=1"  class="card-img-top" alt="...">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Acheter cette photo</a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <img src="https://loremflickr.com/320/240?random=100"  class="card-img-top" alt="...">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Acheter cette photo</a>
          </div>
        </div>
      </div>
    </div>

      

<div class="card rounded shadow-sm mb-3">
      <h6 class="card-header">Event feed</h6>
      <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
          <span><strong class="text-gray-dark">@username</strong> is interested.</span>
        </li>

        <li class="list-group-item d-flex">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#e83e8c"></rect><text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text></svg>
          <span><strong class="text-gray-dark">@username</strong> will attend the event.</span>
        </li>

        <li class="list-group-item d-flex">
        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#6f42c1"></rect><text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text></svg>
          <span><strong class="text-gray-dark">@username</strong> will attend the event.</span>
        </li>
      </ul>
      </div>
      </div>        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/static_pages/show_product.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <link rel="stylesheet" href="bootstrap.css" media="all">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-success  bg-opacity-25" ">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="<%= root_path %>">Samourai Photo Cats</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4 ">
        <li class="nav-item "><a class="btn btn-outline-secondary btn-sm" href="<%= new_user_session_path %>">Se connecter</a></li>
        <li class="nav-item"><a class=" btn btn-outline-secondary btn-sm" href="<%= new_user_registration_path %>">S'inscrire</a></li>                     
      </ul>
    </div>
  </div>
</nav>

<body>
  <div class="container">
    <div class="card mb-4">
      <div class="row g-0">
        <div class="col-lg-8">
          <img src="https://loremflickr.com/320/240?random=2" class="img-fluid rounded-start">
        </div>
        <div class="col-lg-4">
          <div class="card-body h-100">
            <div class="list-group">
              <p class="mb-5"><i class="far fa-calendar"></i> 2021-12-24</p>
              <p class="h3 mb-auto"></p>
              <p class="text-secondary">julien <span class="ms-1 badge bg-primary">Follow</span></p>
            </div>
            <p class="position-absolute bottom-0 mb-3 text-secondary">$200</p>
          </div>
        </div>
      </div>
    </div>
    <div>
      <div class="pb-3 border-bottom d-flex">
        <p class="align-middle mb-0 ms-3"><i class="fas fa-share me-3"></i> <i class="far fa-heart"></i></p>
        <button class="align-middle btn btn-primary btn-sm ms-auto me-3">Acheter cette photo</button>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-lg-8">
        <p class="mb-5">Etiam placerat dolor ac erat imperdiet feugiat. Nam sit.</p>
        <p class="h4"></p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec tristique metus, ut tristique neque. Ut nisi dolor, rutrum at rutrum vel, laoreet sit amet elit. Nulla commodo, risus in lacinia molestie, libero ligula ultricies odio, auctor ultricies elit lectus sed mauris. Sed eu diam luctus, facilisis elit imperdiet, suscipit quam. Proin aliquam at neque id pretium. Aliquam ac mi vitae nibh rutrum vulputate quis in nisl. Donec sed varius elit. Etiam rutrum metus ipsum, at sagittis sapien iaculis ac. Phasellus suscipit in ante vel gravida.</p>

        <p>Proin elementum dignissim sollicitudin. Donec porta magna pulvinar ullamcorper faucibus. Nunc sed elit sapien. Donec aliquam est non sagittis ultricies. Donec id velit venenatis, euismod metus non, suscipit sapien. Praesent mollis vitae magna ac rhoncus. Vivamus sit amet pellentesque metus. Mauris eu massa vitae justo porta sollicitudin. Nulla mollis erat arcu, ac hendrerit nisi mattis a. Donec ornare lacinia dui, sed dignissim ipsum sodales non. Aliquam ante urna, semper nec ante eu, hendrerit ullamcorper libero. Nullam vel ipsum feugiat, cursus dolor vel, maximus libero.</p>
       

        <p class="mt-5 mb-3">Tags</p>
        <p>
          <span class="badge rounded-pill bg-primary">#chats</span>
          <span class="badge rounded-pill bg-primary">#Chatons</span>
          <span class="badge rounded-pill bg-primary">#Croquette</span>
          <span class="badge rounded-pill bg-primary">#Mignon</span>
        </p>

        <p class="mt-5 mb-3">Share with friends</p>
        <p class="mb-5">
          <i class="me-3 fab fa-twitter"></i>
          <i class="me-3 fab fa-facebook"></i>
          <i class="me-3 fab fa-linkedin"></i>
          <i class="me-3 fas fa-envelope"></i>
        </p>

      </div>
      <div class="col-lg-4">
        <p><i class="fas fa-map-marked me-3"></i><b></b></p>
      </div>
    </div>
  </div>
</body>
</html>