config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  get 'static_pages/secret'
  devise_for :users
  resources :users
  resources :items
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_one :user
  has_many :join_table_cart_items
  has_many :items, through: :join_table_cart_items

  def total
    total = 0
    self.items.each do |item|
      total += item.price
    end
    return total
  end

end

app/models/create_join_order_item.rb
class CreateJoinOrderItem < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :picture
  validates :picture,
            presence: true

end

app/models/join_cart_item.rb
class JoinCartItem < ApplicationRecord

  before_create :already_exist?
  after_create :null

  belongs_to :cart
  belongs_to :item
end

app/models/join_order_item.rb
class JoinOrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item



end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord

  belongs_to :cart
  belongs_to :item

end

app/models/order.rb
class Order < ApplicationRecord

  after_create :order_mail
  after_create :order_cart

  belongs_to :user

  has_many :join_order_items
  has_many :items, through: :join_order_items

 
  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  after_create :welcome_send
    
   after_create :user_cart
  has_one :cart, dependent: :destroy
  has_many :items, through: :carts
  has_many :orders


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


   

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end

    def user_cart
      Cart.create(user_id: self.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user, only: [:show]

  def index
    @carts = Cart.all
    @carts_length = (Cart.find_by(user_id: current_user.id)).items.length
  end  

  def show
    @cart = Cart.find_by(user_id: params[:id])
  end
  
  def update
    @cart = Cart.find_by(user_id: current_user.id)
    new_item = JoinTableCartItem.create(cart_id: @cart.id, item_id: params[:id])

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end

  def destroy
    @user = current_user
    @item = Item.find_by(id: params[:id])
    @cart = Cart.find_by(user_id: current_user.id)
    @cart_item = JoinTableCartItem.find_by(cart_id: @cart.id, item_id: @item.id).destroy

    respond_to do |format|
      format.html { redirect_to cart_path(@user.id) }
    end
  end

  private

  def set_current_user
    @cart = Cart.find_by(user_id: params[:id])
    if current_user.id != @cart.user_id
      redirect_to root_path
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 before_action :authenticate_user!, except: [:index, :show]
  # before_action :authenticate_user!

  def index
  	@items = Item.all
  end

  def show
  	@item = Item.find(params[:id])
  end

   def update
   
    @cart = Cart.find_by(user_id: current_user.id)
    new_item = JoinTableCartItem.create(cart_id: @cart.id, item_id: params[:id])

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @item_price = params[:item_price]
  end

  def create
    # Before the rescue, at the beginning of the method
    @stripe_amount = 500
    begin
      customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
      })
      charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @stripe_amount,
      description: "Achat d'un produit",
      currency: 'eur',
      })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_order_path
    end
# After the rescue, if the payment succeeded
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_exists?, :check_user, only: [:show]
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_test_helper.rb
module BootstrapTestHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<div class="container mt-5">
  <div class="card my-3 text-center card-center">
    <h2 class="action-banner card-header">Mon panier</h2>
    
      <% if @cart.items.length != 0 %>
      <% end %>
      <% @cart.items.each do |item| %>
      <hr>
        <div class="card-body" id=<%= JoinTableCartItem.find_by(cart_id: @cart.id, item_id: item.id).id %>>
          <div class="float-left mr-5">
            <span class="cart-image"><%= image_tag item.image_url, height: "200px;" %></span>
          </div>
          <div class="float-left mb-5 mr-5 text-left">
            <h5 class="mb-4">Nom du Chat : <span class="card-text"><%= item.title %></span></h5>
            <h5 class="mb-4">Prix de la Photo : <span class="card-text"><%= item.price %></span> €</h5>
            <div class="cart-button float-left">
              <%= link_to 'Supprimer du panier', cart_path(item.id), method: :delete, class: "btn btn-danger float-left" %> 
            </div>
              </div>

              </div>
            <% end %> 
          </div>

        <% if @cart.items.length != 0 %>
          <div class="container mt-5">
            <div class="card mt-2 mb-3 text-center card-center">
              <h5 class="mb-4 action-banner" >Prix total : <%= @cart.total %> €</h5>
               <a class="btn btn-warning btn-sm" href="<%= new_order_path(item_price: @cart.total) %>">PAYER</a>
              <p>Une fois le réglement effectué vous recevrez vos photos de chats directement sur votre email !</p>
        <% else %>
              <p> Votre panier est vide </p>
        <% end %>
            </div>
          </div>

          <div class="container mt-5 mb-3 text-center w-50 card-center">
            
  </div>    

</div>

app/views/carts/update.js.erb
cart = document.querySelector('span.badge');

number = cart.innerHTML;
calc = parseInt(number, 10) + 1;
cart.innerHTML = calc;

app/views/items/index.html.erb
<!-- JUMBOTRON -->

  <div class="container py-5">
    <div class="jumbotron text-white jumbotron-image shadow" style="background-image: url(https://www.nipponconnection.fr/wp-content/uploads/2014/09/Sans-titre-1.jpg);">
      <h2 class="mb-4 "><p style="text-align:center">Tous les chats</h2></p>
    </div>
  </div>

 <div class="container">
    
    <div class="row row-cols-1 row-cols-md-3 g-4">

  <% @items.each do |item| %>
              
      <div class="col-sm-6 col-lg-4">
        <%# <div class="card"> %>
           <div class="card text-white bg-primary mb-3" >
          <a href="<%= item_path(item.id) %>">
            <%= image_tag item.image_url, :alt => "cat image",class:"card-img img-fluid ",style: "" %>
          </a>

       
            <div class="card-body">
              <h5 class="card-title"><%=item.title%></h5>
              <p class="card-text"><%=item.description%></p>

              <div class="d-flex align-items-center ">

              <%# <div class="card-btn"> %>
              <a href="<%= item_path(item.id) %>" class="ml-2 btn btn-warning" >Voir la photo</a>
                  <% if user_signed_in?%>
                  <%= link_to cart_path(item.id), class: "color_cart", remote: true, method: "PUT" do %>
                    <i class=" ml-3 text-warning fas fa-cart-arrow-down fa-2x"></i>
                  <% end %>
                <% end %>
              <%# </div> %>
              </div>

            </div>
          </div>
        <%# </div> %>
      </div>

  <%end%>
    

app/views/items/show.html.erb
  <div class="container">
    <div class="card m-4">
      <div class="row g-4 d-flex justify-content-center">
        <div class="col-lg-10">
          <%# <img src="https://loremflickr.com/320/240?random=2" class="img-fluid rounded-start"> %>
          <p align="center">
            <%= image_tag @item.image_url, :alt => "cat image",style: "height: 500px",class: "img-fluid rounded-start" %>
            </p>
        </div>
        <div class="col-lg-4" >
          <div class="card-body h-100 d-flex justify-content-center">
            <div class="list-group">
              
            </div>
             
            <p class=""><%=@item.price%> €</p>
          </div>
        </div>
      </div>
    </div>
    <div>    
           <div class="pb-3 border-bottom text-center">    
                  <% if user_signed_in?%>
                  <%= link_to cart_path(@item.id), class: "color_cart", remote: true, method: "PUT" do %>
                  <button type="button" class="btn btn-warning" >Ajouter au panier</button>


                  <% end %>
                <% end %>
      </div>
    </div>
    <div class="row mt-5 d-flex justify-content-center">
      <div class="col-lg-8">
         <h2><p style="text-align:center"><%=@item.title%></h2></p>
        <p class="h4"></p>

        <h5><p style="text-align:center"><%=@item.description%></h5></p>       

        
      <footer class="text-center text-white" style="background-color: rgb(197,225,212);">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Images -->
    <section class="">
      <div class="row">
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img src="https://loremflickr.com/320/240?random=12"
              class="w-100"
            />
            <a href="#!">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);" ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img src="https://loremflickr.com/320/240?random=29"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img src="https://loremflickr.com/320/240?random=2"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img src="https://loremflickr.com/320/240?random=23"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img src="https://loremflickr.com/320/240?random=25"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img src="https://loremflickr.com/320/240?random=200"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
      </div>
    </section>
    <!-- Section: Images -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">PizzaCats</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>
<h2>Thanks, you paid <strong><%=@item_price %></strong>!</h2>

app/views/orders/new.html.erb
<div class="container text-center mt-5 ">

<div class="card" style="width: 28rem;">
    <%= image_tag "pizcats", :alt => "cat image",class:"rounded card-img img-fluid ",style: "" %>
  <div class="card-body d-flex justify-content-center">
    <h5 class="card-title ">Samourai Photo Cats</h5>
    <p class="card-text">Des photos de qualité et des pizzas cats à la sauce samourai.</p>
    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>

<div>

<%= form_tag orders_path do %>
<article style="text-align: center;">
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <label class="amount m-5">
    <h4><%=@item_price  %> €</h4>
  </label>
</article> 
</div>
 </div>


<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Achat d'un produit"
    data-amount=<%=@item_price.to_f*100 %>
    data-locale="auto">
</script>
<% end %>

app/views/orders/show.html.erb
<!--FONTS-->
 
 <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Goblin+One&amp;display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Mate+SC&amp;display=swap" rel="stylesheet">


<h1>Votre panier</h1>
<div class="card border-light mb-3 " >
  <div class="card-header text-white bg-dark">
    Votre panier:
  </div>
  <ul class="list-group list-group-flush border-right-0">
    <% @cart.in_cart.each do |item| %>
      <li class="list-group-item" id="<%= item.id%>">
        <div class="row">
            <div class="col-md-2">
              <%= image_tag item.picture, width: "150" %>
            </div>
            <div class="col-md-9">
                <%= link_to item.title, item_path(item), style:"font-size: 1.5em;" %><br>
              <strong>
                <%= item.price %>€
              </strong>
              <br>
              <strong>
                Quantité: <%= item.quantity(@cart.id)%> X 
              </strong>
            </div>
            <div class="col-md-1">
              <%= link_to "<i class='fa fa-trash'></i>".html_safe, cart_path(item), method: "DELETE",class: "btn btn-danger", remote: true %>
            </div>
        </div>
      </li>
    <% end %>
      <div class="card-footer  text-right">
      <% if @cart.total == 0 %>
        <h4>Total: <%= @cart.total%> €</h4>
        <%= link_to "Payer", root_path, class:"btn btn-outline-primary btn-lg" %> 
      <% else %>
        <% if user_signed_in? %>
    <!-- STRIPE -->
        <div id="stripe">
          <%= render 'stripe'%>
        </div>
    <!-- End of STRIPE -->        
        <% else %>
        <div id="stripe">
          <%= render 'guest_total'%>
        </div>
        <% end %>
      <% end %>

      </div>    
  </ul>
</div>

app/views/users/_form.htlml.erb
<%= form_with(model: user, local: true, method: :put) do |form| %>
   <div class="form-group">
      <%= form.text_field :first_name, class:"form-control", placeholder:"Prénom" %>
   </div>

   <div class="form-group">
      <%= form.text_field :first_name, class:"form-control", placeholder:"Nom" %>
   </div>

   <div class="form-group">
      <%= form.text_field :first_name, class:"form-control", placeholder:"Date de naissance" %>
   </div>

   <div class="form-group">
      <%= form.text_field :first_name, class:"form-control", placeholder:"Description" %>
   </div>

    <div class="actions text-center">
        <%= form.submit%>
    </div>

<% end %>

<br><br>    

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<main class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <h1>Editer votre profil</h1>

            <%= render 'form', user: @user %>
            <div class="text-center">
                <%= link_to 'Voir le profil', @user, class:"btn btn-warning" %> |
                <%= link_to '« Retour Accueil', root_path, class:"btn btn-outline-warning" %>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    
</main>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<h1 class="text-center mt-4"> Bienvenue sur votre profil <%=@user.first_name%> <%=@user.last_name%></h1>
  
  
<div class="d-flex justify-content-center mt-5">
        <div class="card w-50">
          <div class="card-body">
            <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
            <p class="card-text"><%= @user.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= @user.email %></li>
            <li class="list-group-item"><%= @user.birthdate %></li>
            <li class="list-group-item"><%= @user.adress %></li>
          </ul>
          <div class="card-body text-center">
            <%if current_user.id == @user.id %>
              <%= link_to 'Editer le compte', edit_user_registration_path, class:"btn btn-outline-success" %> |
              <%= link_to 'Editer le profil', edit_user_path, class:"btn btn-success" %>
            <% end %>
          </div>
        </div>
    </div>

    <div class="text-center mt-3">
        <%= link_to '« Retour Accueil', root_path, class:"btn btn-warning" %>
    </div>
  <br>
  <div class="my-5">
    <h2 > Vos commandes </h2><br>
    
    <% current_user.orders.each_with_index do |order, i| %>
      <div class="accordion" id="accordionExample">
        <div class="card">
          <div class="card-header" id="heading<%= i %>">
            <h2 class="mb-0">
              <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse<%= i %>" aria-expanded="true" aria-controls="collapse<%= i %>">
                <b> Commande du <%= order.created_at.strftime('%d/%m/%Y à %H:%M') %> d'un montant de <%= order.total %>€</b> 
              </button>
            </h2>
          </div>
      
          <div id="collapse<%= i %>" class="collapse" aria-labelledby="heading<%= i %>" data-parent="#accordionExample">
            <div class="card-body">
              <p> Contenu : </p>
              <ul>
              <% order.items.each do |item| %>
                <li class="d-flex justify-content-between">
                  <%= item.title %> 
                  <%= link_to "Voir l'article", item_path(item.id) %>
                </li> 
              <% end %>
              </ul>
        
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>